import numpy as np
listarray = np.array([[[[0,1,2],[3,4,5],[6,7,8]]]])
print(listarray)
print(listarray.shape)
print(type(listarray))
print(listarray.ndim)
print(listarray.shape)
print(listarray.dtype)
listarray = np.array({0,1,2,3,4,5,6,7,8  })
print(listarray.dtype)