import numpy as np
zeros = np.zeros((4,8))
print(zeros)
rng = np.arange(21)
print(rng)
lspace = np.linspace(1,15,5)
print(lspace)
emp = np.empty((3,2))
print(emp)
emp_like = np.empty_like(zeros)
print(emp_like)
ide = np.identity(12)
print(ide)
zeros = zeros.reshape(16,2)
zeros = zeros.ravel()
print(zeros)